
/*
 * This file was generated by the SOM Compiler.
 * FileName: icobtn.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define VRIconButton_Class_Source
#include "icobtn.ih"

/*
 *  VRIconButtonInstance_somInit
 */

SOM_Scope void   SOMLINK VRIconButtonInstance_somInit(VRIconButton *somSelf)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_somInit");

    parent_somInit(somSelf);
}

/*
 *  VRIconButtonInstance_somUninit
 */

SOM_Scope void   SOMLINK VRIconButtonInstance_somUninit(VRIconButton *somSelf)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_somUninit");

    parent_somUninit(somSelf);
}

/*
 *  VRIconButtonInstance_vrLocalCreateWindow
 */

SOM_Scope HWND   SOMLINK VRIconButtonInstance_vrLocalCreateWindow(VRIconButton *somSelf,
		PBOOL visible)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrLocalCreateWindow");

    return (parent_vrLocalCreateWindow(somSelf,visible));
}

/*
 *  VRIconButtonInstance_vrSet_Caption
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_Caption(VRIconButton *somSelf,
		PSZ str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_Caption");

    return (parent_vrSet_Caption(somSelf,str));
}

/*
 *  VRIconButtonInstance_vrGet_Caption
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_Caption(VRIconButton *somSelf,
		PSZ *str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_Caption");

    return (parent_vrGet_Caption(somSelf,str));
}

/*
 *  VRIconButtonInstance_vrSet_PicturePath
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_PicturePath(VRIconButton *somSelf,
		PSZ str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_PicturePath");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrGet_PicturePath
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_PicturePath(VRIconButton *somSelf,
		PSZ *str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_PicturePath");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrSet_ResizePicture
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_ResizePicture(VRIconButton *somSelf,
		BOOL on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_ResizePicture");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrGet_ResizePicture
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_ResizePicture(VRIconButton *somSelf,
		BOOL *on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_ResizePicture");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrSet_TextPosition
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_TextPosition(VRIconButton *somSelf,
		PSZ str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_TextPosition");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrGet_TextPosition
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_TextPosition(VRIconButton *somSelf,
		PSZ *str)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_TextPosition");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrSet_Pushed
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_Pushed(VRIconButton *somSelf,
		BOOL on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_Pushed");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrGet_Pushed
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_Pushed(VRIconButton *somSelf,
		BOOL *on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_Pushed");

    return (bool) 0;
}

/*
 *  VRIconButtonInstance_vrSet_Autosize
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrSet_Autosize(VRIconButton *somSelf,
		BOOL on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrSet_Autosize");

    return (parent_vrSet_Autosize(somSelf,on));
}

/*
 *  VRIconButtonInstance_vrGet_Autosize
 */

SOM_Scope bool   SOMLINK VRIconButtonInstance_vrGet_Autosize(VRIconButton *somSelf,
		BOOL *on)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrGet_Autosize");

    return (parent_vrGet_Autosize(somSelf,on));
}

/*
 *  VRIconButtonInstance_vrWM_CONTROL
 */

SOM_Scope MRESULT   SOMLINK VRIconButtonInstance_vrWM_CONTROL(VRIconButton *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrWM_CONTROL");

    return (MRESULT) 0;
}

/*
 *  VRIconButtonInstance_vrWM_PAINT
 */

SOM_Scope MRESULT   SOMLINK VRIconButtonInstance_vrWM_PAINT(VRIconButton *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrWM_PAINT");

    return (MRESULT) 0;
}

/*
 *  VRIconButtonInstance_vrWM_MATCHMNEMONIC
 */

SOM_Scope MRESULT   SOMLINK VRIconButtonInstance_vrWM_MATCHMNEMONIC(VRIconButton *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2)
{
    VRIconButtonData *somThis = VRIconButtonGetData(somSelf);
    VRIconButtonMethodDebug("VRIconButton","VRIconButtonInstance_vrWM_MATCHMNEMONIC");

    return (MRESULT) 0;
}

#undef SOM_CurrentClass
#define SOM_CurrentClass SOMMeta
/*
 *  VRIconButtonClass_vrLocalClassInit
 */

SOM_Scope bool   SOMLINK VRIconButtonClass_vrLocalClassInit(M_VRIconButton *somSelf)
{
    /* M_VRIconButtonData *somThis = M_VRIconButtonGetData(somSelf); */
    M_VRIconButtonMethodDebug("M_VRIconButton","VRIconButtonClass_vrLocalClassInit");

    return (parent_vrLocalClassInit(somSelf));
}

/*
 *  VRIconButtonClass_vrLocalWindowClassInit
 */

SOM_Scope bool   SOMLINK VRIconButtonClass_vrLocalWindowClassInit(M_VRIconButton *somSelf)
{
    /* M_VRIconButtonData *somThis = M_VRIconButtonGetData(somSelf); */
    M_VRIconButtonMethodDebug("M_VRIconButton","VRIconButtonClass_vrLocalWindowClassInit");

    return (parent_vrLocalWindowClassInit(somSelf));
}

/*
 *  VRIconButtonClass_somInit
 */

SOM_Scope void   SOMLINK VRIconButtonClass_somInit(M_VRIconButton *somSelf)
{
    /* M_VRIconButtonData *somThis = M_VRIconButtonGetData(somSelf); */
    M_VRIconButtonMethodDebug("M_VRIconButton","VRIconButtonClass_somInit");

    parent_somInit(somSelf);
}

/*
 *  VRIconButtonClass_somUninit
 */

SOM_Scope void   SOMLINK VRIconButtonClass_somUninit(M_VRIconButton *somSelf)
{
    /* M_VRIconButtonData *somThis = M_VRIconButtonGetData(somSelf); */
    M_VRIconButtonMethodDebug("M_VRIconButton","VRIconButtonClass_somUninit");

    parent_somUninit(somSelf);
}
