
/*
 * This file was generated by the SOM Compiler.
 * FileName: tabdlg.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef tabdlg_h
#define tabdlg_h


#include <som.h>

/*
 * Define the class name as an object type
 */
#ifndef VRTabbedDialog
#define VRTabbedDialog SOMAny
#endif
#include "notebk.h"

/*
 * Passthru lines: File: "C.h", "after"
 */
#ifdef __WATCOMC__
    #pragma aux VRTabbedDialogCClassData "*"
    #pragma aux VRTabbedDialogClassData "*"
    #pragma aux M_VRTabbedDialogCClassData "*"
    #pragma aux M_VRTabbedDialogClassData "*"
#endif

#define VRTabbedDialog_MajorVersion 1
#define VRTabbedDialog_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define VRTabbedDialogNewClass c
#pragma linkage(c, system)
#define VRTabbedDialogClassData d
#define VRTabbedDialogCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define VRTabbedDialog_classObj VRTabbedDialogClassData.classObject
#define _VRTabbedDialog VRTabbedDialog_classObj

/*
 * New and Renew macros for VRTabbedDialog
 */
#define _VRTabbedDialogNew() (_somNew(VRTabbedDialogClassData.classObject))
#define VRTabbedDialogNew() \
	( VRTabbedDialogClassData.classObject \
		? _VRTabbedDialogNew() \
		: ( VRTabbedDialogNewClass(VRTabbedDialog_MajorVersion, VRTabbedDialog_MinorVersion), _VRTabbedDialogNew() ) )
#define VRTabbedDialogRenew(buf) \
	( _somRenew(VRTabbedDialogClassData.classObject, buf) )

/*
 * Override method: somInit
 */
#define VRTabbedDialog_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * Override method: somUninit
 */
#define VRTabbedDialog_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * Override method: vrLocalCreateWindow
 */
#define VRTabbedDialog_vrLocalCreateWindow(somSelf,visible) \
	VRCore_vrLocalCreateWindow(somSelf,visible)

/*
 * Override method: vrWM_CONTEXTMENU
 */
#define VRTabbedDialog_vrWM_CONTEXTMENU(somSelf,hWnd,msg,mp1,mp2) \
	VRVisible_vrWM_CONTEXTMENU(somSelf,hWnd,msg,mp1,mp2)

/*
 * Override method: vrWM_COMMAND
 */
#define VRTabbedDialog_vrWM_COMMAND(somSelf,hWnd,msg,mp1,mp2) \
	VRManager_vrWM_COMMAND(somSelf,hWnd,msg,mp1,mp2)

/*
 * Override method: vrWM_CHAR
 */
#define VRTabbedDialog_vrWM_CHAR(somSelf,hWnd,msg,mp1,mp2) \
	VRVisible_vrWM_CHAR(somSelf,hWnd,msg,mp1,mp2)

/*
 * New Method: vrSet_TabPosition
 */
typedef bool    SOMLINK somTP_VRTabbedDialog_vrSet_TabPosition(VRTabbedDialog *somSelf,
		PSZ str);
#pragma linkage(somTP_VRTabbedDialog_vrSet_TabPosition, system)
typedef somTP_VRTabbedDialog_vrSet_TabPosition *somTD_VRTabbedDialog_vrSet_TabPosition;
#define somMD_VRTabbedDialog_vrSet_TabPosition "----"
#define VRTabbedDialog_vrSet_TabPosition(somSelf,str) \
    (SOM_Resolve(somSelf, VRTabbedDialog, vrSet_TabPosition) \
	(somSelf,str))
#define _vrSet_TabPosition VRTabbedDialog_vrSet_TabPosition

/*
 * New Method: vrGet_TabPosition
 */
typedef bool    SOMLINK somTP_VRTabbedDialog_vrGet_TabPosition(VRTabbedDialog *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRTabbedDialog_vrGet_TabPosition, system)
typedef somTP_VRTabbedDialog_vrGet_TabPosition *somTD_VRTabbedDialog_vrGet_TabPosition;
#define somMD_VRTabbedDialog_vrGet_TabPosition "----"
#define VRTabbedDialog_vrGet_TabPosition(somSelf,str) \
    (SOM_Resolve(somSelf, VRTabbedDialog, vrGet_TabPosition) \
	(somSelf,str))
#define _vrGet_TabPosition VRTabbedDialog_vrGet_TabPosition

/*
 * New Method: vrSet_TabDirection
 */
typedef bool    SOMLINK somTP_VRTabbedDialog_vrSet_TabDirection(VRTabbedDialog *somSelf,
		PSZ str);
#pragma linkage(somTP_VRTabbedDialog_vrSet_TabDirection, system)
typedef somTP_VRTabbedDialog_vrSet_TabDirection *somTD_VRTabbedDialog_vrSet_TabDirection;
#define somMD_VRTabbedDialog_vrSet_TabDirection "----"
#define VRTabbedDialog_vrSet_TabDirection(somSelf,str) \
    (SOM_Resolve(somSelf, VRTabbedDialog, vrSet_TabDirection) \
	(somSelf,str))
#define _vrSet_TabDirection VRTabbedDialog_vrSet_TabDirection

/*
 * New Method: vrGet_TabDirection
 */
typedef bool    SOMLINK somTP_VRTabbedDialog_vrGet_TabDirection(VRTabbedDialog *somSelf,
		PSZ *str);
#pragma linkage(somTP_VRTabbedDialog_vrGet_TabDirection, system)
typedef somTP_VRTabbedDialog_vrGet_TabDirection *somTD_VRTabbedDialog_vrGet_TabDirection;
#define somMD_VRTabbedDialog_vrGet_TabDirection "----"
#define VRTabbedDialog_vrGet_TabDirection(somSelf,str) \
    (SOM_Resolve(somSelf, VRTabbedDialog, vrGet_TabDirection) \
	(somSelf,str))
#define _vrGet_TabDirection VRTabbedDialog_vrGet_TabDirection

/*
 * New Method: vrWM_BUTTON1DOWN
 */
typedef MRESULT    SOMLINK somTP_VRTabbedDialog_vrWM_BUTTON1DOWN(VRTabbedDialog *somSelf,
		HWND hWnd,
		ULONG msg,
		MPARAM mp1,
		MPARAM mp2);
#pragma linkage(somTP_VRTabbedDialog_vrWM_BUTTON1DOWN, system)
typedef somTP_VRTabbedDialog_vrWM_BUTTON1DOWN *somTD_VRTabbedDialog_vrWM_BUTTON1DOWN;
#define somMD_VRTabbedDialog_vrWM_BUTTON1DOWN "----"
#define VRTabbedDialog_vrWM_BUTTON1DOWN(somSelf,hWnd,msg,mp1,mp2) \
    (SOM_Resolve(somSelf, VRTabbedDialog, vrWM_BUTTON1DOWN) \
	(somSelf,hWnd,msg,mp1,mp2))
#define _vrWM_BUTTON1DOWN VRTabbedDialog_vrWM_BUTTON1DOWN

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK VRTabbedDialogNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(VRTabbedDialogNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct VRTabbedDialogClassDataStructure {
	SOMAny *classObject;
	somMToken vrSet_TabPosition;
	somMToken vrGet_TabPosition;
	somMToken vrSet_TabDirection;
	somMToken vrGet_TabDirection;
	somMToken vrWM_BUTTON1DOWN;
	somMToken vrWM_CONTEXTMENU;
} VRTabbedDialogClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct VRTabbedDialogCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} VRTabbedDialogCClassData;

#endif       /* tabdlg_h */

/*
 * This file was generated by the SOM Compiler.
 * FileName: tabdlg.h.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emith: 1.11
 */

#ifndef tabdlg_mh
#define tabdlg_mh


/*
 * Define the class name as an object type
 */
#ifndef M_VRTabbedDialog
#define M_VRTabbedDialog SOMAny
#endif

#define M_VRTabbedDialog_MajorVersion 1
#define M_VRTabbedDialog_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_VRTabbedDialogNewClass c
#pragma linkage(c, system)
#define M_VRTabbedDialogClassData d
#define M_VRTabbedDialogCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_VRTabbedDialog_classObj M_VRTabbedDialogClassData.classObject
#define _M_VRTabbedDialog M_VRTabbedDialog_classObj

/*
 * New and Renew macros for M_VRTabbedDialog
 */
#define _M_VRTabbedDialogNew() (_somNew(M_VRTabbedDialogClassData.classObject))
#define M_VRTabbedDialogNew() \
	( M_VRTabbedDialogClassData.classObject \
		? _M_VRTabbedDialogNew() \
		: ( M_VRTabbedDialogNewClass(M_VRTabbedDialog_MajorVersion, M_VRTabbedDialog_MinorVersion), _M_VRTabbedDialogNew() ) )
#define M_VRTabbedDialogRenew(buf) \
	( _somRenew(M_VRTabbedDialogClassData.classObject, buf) )

/*
 * Override method: vrLocalClassInit
 */
#define M_VRTabbedDialog_vrLocalClassInit(somSelf) \
	M_VRCore_vrLocalClassInit(somSelf)

/*
 * Override method: vrLocalWindowClassInit
 */
#define M_VRTabbedDialog_vrLocalWindowClassInit(somSelf) \
	M_VRCore_vrLocalWindowClassInit(somSelf)

/*
 * Override method: somInit
 */
#define M_VRTabbedDialog_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * Override method: somUninit
 */
#define M_VRTabbedDialog_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: vrShowHelp
 */
typedef bool    SOMLINK somTP_M_VRTabbedDialog_vrShowHelp(M_VRTabbedDialog *somSelf,
		HWND root_frame);
#pragma linkage(somTP_M_VRTabbedDialog_vrShowHelp, system)
typedef somTP_M_VRTabbedDialog_vrShowHelp *somTD_M_VRTabbedDialog_vrShowHelp;
#define somMD_M_VRTabbedDialog_vrShowHelp "----"
#define M_VRTabbedDialog_vrShowHelp(somSelf,root_frame) \
    (SOM_Resolve(somSelf, M_VRTabbedDialog, vrShowHelp) \
	(somSelf,root_frame))
#define _vrShowHelp M_VRTabbedDialog_vrShowHelp

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMAny * SOMLINK M_VRTabbedDialogNewClass(integer4 scemajorVersion,
		integer4 sceminorVersion);
#pragma linkage(M_VRTabbedDialogNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_VRTabbedDialogClassDataStructure {
	SOMAny *classObject;
	somMToken vrShowHelp;
} M_VRTabbedDialogClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_VRTabbedDialogCClassDataStructure {
	somMethodTab *parentMtab;
	somDToken instanceDataToken;
} M_VRTabbedDialogCClassData;

#endif       /* tabdlg_h */
